### ISSUE TITLE
Enhance blog page

### ISSUE THREAD

**Issue by coding-geek21** [Feminine-Divine/Woodog#113]
### 🐣 Is your feature request related to a problem? Please describe.

Improve the design of blog page, like adding more sections like featured, popular etc.. and adding pagination 

### 📹 Screenshots or Video or GIF

---

**Note:**
* Do mention if you're working on this issue under ` LGM SOC 2021 `.
* If you want to work on any issue, you should check if it has already been assigned to anyone.

**Comment by Aaishpra** [comment]
Go for it
