### ISSUE TITLE
Add Chatbot

### ISSUE THREAD

**Issue by coding-geek21** [Feminine-Divine/Woodog#129]
### 🐣 Is your feature request related to a problem? Please describe.

Chat bots can be added to improve user experience 

### 📹 Screenshots or Video or GIF

---

**Note:**
* Do mention if you're working on this issue under ` LGM SOC 2021 `.
* If you want to work on any issue, you should check if it has already been assigned to anyone.

**Comment by khushishikhu** [comment]
@coding-geek21 go ahead
