### ISSUE TITLE
Enhance and Fix Bugs in Service page

### ISSUE THREAD

**Issue by coding-geek21** [Feminine-Divine/Woodog#137]
### 🐞 Describe the Bug

![image](https://user-images.githubusercontent.com/53329034/125155680-30c14200-e17f-11eb-96d9-fca90c753e47.png)
![image](https://user-images.githubusercontent.com/53329034/125160442-7d664680-e19a-11eb-93fe-f3b1a91782b4.png)

-footer gets distorted
- I also want to change the font color, text size ,style and background color according to UI, As it's not readable

### 📹 Screenshots or Video or GIF

---

**Note:**
* Do mention if you're working on this issue under ` LGM SOC 2021 `.
* If you want to work on any issue, you should check if it has already been assigned to anyone.

**Comment by hariramjp777** [comment]
assigned :+1: @coding-geek21
