### ISSUE TITLE
Design  blog content page

### ISSUE THREAD

**Issue by coding-geek21** [Feminine-Divine/Woodog#140]
### 🐣 Is your feature request related to a problem? Please describe.

We have blog page, as an extension i want to design a blog content page
When clicking the Read more button it will redirect to blog content page.

### 📹 Screenshots or Video or GIF

---

**Note:**
* Do mention if you're working on this issue under ` LGM SOC 2021 `.
* If you want to work on any issue, you should check if it has already been assigned to anyone.

**Comment by hariramjp777** [comment]
assigned :+1: @coding-geek21
