### ISSUE TITLE
Create Models for Gallery page

### ISSUE THREAD

**Issue by coding-geek21** [Feminine-Divine/Woodog#141]
### 🐣 Is your feature request related to a problem? Please describe.

I want to create models for gallery page, so that admin can directly upload pictures into the database

### 📹 Screenshots or Video or GIF

---

**Note:**
* Do mention if you're working on this issue under ` LGM SOC 2021 `.
* If you want to work on any issue, you should check if it has already been assigned to anyone.

**Comment by hariramjp777** [comment]
assigned :+1: @coding-geek21
