### ISSUE TITLE
Make an Issue template for documentation issues

### ISSUE THREAD

**Issue by khushishikhu** [Feminine-Divine/Woodog#15]
### 🐣 Is your feature request related to a problem? Please describe.

The 
The template for Bug request and Feature request have already been made. The documentation issue template isn't there.

### 💡 Describe the solution you'd like

---

**Note:**
* Do mention if you're working on this issue under ` LGM SOC 2021 `.
* If you want to work on any issue, you should check if it has already been assigned to anyone.

**Comment by coding-geek21** [comment]
I would like to work on this issue, Can you please assign me @hariramjp777 @khushishikhu

**Comment by hariramjp777** [comment]
> I would like to work on this issue, Can you please assign me @hariramjp777 @khushishikhu

Go ahead @coding-geek21

**Comment by coding-geek21** [comment]
> > I would like to work on this issue, Can you please assign me @hariramjp777 @khushishikhu
> 
> Go ahead @coding-geek21

Thank you :)
