### ISSUE TITLE
Fix the height of chatbot

### ISSUE THREAD

**Issue by hariramjp777** [Feminine-Divine/Woodog#160]
### 🐞 Describe the Bug

Fix the height of the chatbot

---

### 📹 Screenshots or Video or GIF

![image](https://user-images.githubusercontent.com/58631762/126268805-8387e912-376f-40ab-a01b-8d685a3a37fc.png)

---

### 💡 Expected behaviour

Height should be reduced.

---

**Note:**
* Do mention if you're working on this issue under ` LGM SOC 2021 `.
* If you want to work on any issue, you should check if it has already been assigned to anyone.

**Comment by coding-geek21** [comment]
I would like to work on this issue please assign this to me @hariramjp777
