### ISSUE TITLE
Fixing the dashboard UI and adding a button to access the dashboard from the navbar

### ISSUE THREAD

**Issue by Saup21** [Feminine-Divine/Woodog#17]
### 🐣 Is your feature request related to a problem? Please describe.

The navbar in the dashboard page is fixed due to which the top row cards are getting chopped off and there is no button to access the dashboard page from index page.

### 💡 Describe the solution you'd like

I'll fix the navbar and add anchor tag in the index page to access the dashboard

### 📹 Screenshots or Video or GIF

---

**Note:**

I am working under LGM-soc. kindly assign me this issue and also add the labels.
Thanks :)

* Do mention if you're working on this issue under ` LGM SOC 2021 `.
* If you want to work on any issue, you should check if it has already been assigned to anyone.

**Comment by Sejal2801** [comment]
Assign it to me

**Comment by Aaishpra** [comment]
@Saup21 are you working here.

**Comment by Saup21** [comment]
I'm a participant

**Comment by Aaishpra** [comment]
Ya I know but are you interested in working on this or we can assign this to @Sejal2801

**Comment by Saup21** [comment]
Yes I'm interested in working on this one. Please assign it to me.

**Comment by Aaishpra** [comment]
Great assigned you!
