### ISSUE TITLE
UI Enhancements for Home Page

### ISSUE THREAD

**Issue by hariramjp777** [Feminine-Divine/Woodog#19]
### 🐣 Is your feature request related to a problem? Please describe.

UI Enhancements for Home Page.

### 💻 Tech Stack

* HTML
* CSS (Bootstrap if comfortable)
* JS
* Django Templates.

### 📹 Screenshots or Video or GIF

![HOME (1)](https://user-images.githubusercontent.com/58631762/121782721-a1992c80-cbc8-11eb-8f84-cfe388d12e80.png)

---

**Note:**
* Do mention if you're working on this issue under ` LGM SOC 2021 `.
* If you want to work on any issue, you should check if it has already been assigned to anyone.

**Comment by coding-geek21** [comment]
I would like to work on this, please assign me @hariramjp777

**Comment by hariramjp777** [comment]
You can start this @coding-geek21 :+1:

**Comment by coding-geek21** [comment]
> You can start this @coding-geek21 👍

Thank you :)

**Comment by Sejal2801** [comment]
Please assign it to me

**Comment by Sejal2801** [comment]
I  can do it perfectly.Please assign it to me

**Comment by Sejal2801** [comment]
Assign it to me..

**Comment by hariramjp777** [comment]
@Sejal2801, This issue is already assigned. We will create new UI pages issues soon. Stay tuned :+1:

**Comment by Sejal2801** [comment]
Okay sir

**Comment by khushishikhu** [comment]
@hariramjp777 as it is quite a big issue. I think we can give some part to another contributor also to work upon. in this issue only and assign it to multiple contributors so that they can collaborate.

**Comment by Sejal2801** [comment]
Yes sir please assign it to me
