### ISSUE TITLE
Updating the README.md since the project does not use PostgreSQL anymore

### ISSUE THREAD

**Issue by Saup21** [Feminine-Divine/Woodog#20]
### Updating the README.md

<h5>PostgreSQL set up section is not needed since the project is using sqlite3 and the README might confuse future contributors</h5>

### 💡 Describe the solution you'd like

<h5>Delete the sections that deal with setting up of PostgreSQL</h5>

### 📹 Screenshots or Video or GIF

---

**Note:**
* Do mention if you're working on this issue under ` LGM SOC 2021 `.
* If you want to work on any issue, you should check if it has already been assigned to anyone.

**Comment by hariramjp777** [comment]
Hi @Saup21, GO ahead :+1:
