### ISSUE TITLE
Add: License and Domain to show the Project, and Fill about section

### ISSUE THREAD

**Issue by thegautamkumarjaiswal** [Feminine-Divine/Woodog#23]
### 💡 Describe the solution you'd like

WE need to add license of project copyrights and We can launch our project to showcase(using any Domain(optional .org)).

### 📹 Screenshots or Video or GIF

---

**Note:**
* Do mention if you're working on this issue under ` LGM SOC 2021 `.
* If you want to work on any issue, you should check if it has already been assigned to anyone.

**Comment by thegautamkumarjaiswal** [comment]
HEY! Admin or maintainer. Please label it under lgmsoc21 and assign me with domain suggestions.

**Comment by Aaishpra** [comment]
@Feminine-Divine/mentor @Feminine-Divine/admin 
@thegautamkumarjaiswal you can use the above tags to reach out to us. It will be easier for us to get a notification and reply then.

**Comment by hariramjp777** [comment]
Yes
