### ISSUE TITLE
Add a program section.

### ISSUE THREAD

**Issue by khushishikhu** [Feminine-Divine/Woodog#24]
### 📚 Documentation File you'd like to improve:

- [ ] README.md
- [ ] CODE_OF_CONDUCT.md
- [ ] CONTRIBUTING.md

### 💡 Describe your ideas briefly on how to improve the documentation

Add a Program section in the Readme. and put the picture of LGM-SOC ( the logo) at the end of the Readme

---

**Note:**
* Do mention if you're working on this issue under ` LGM SOC 2021 `.
* If you want to work on any issue, you should check if it has already been assigned to anyone.

**Comment by ishitakapoor26** [comment]
@Aaishpra pls assign me this issue.

**Comment by hariramjp777** [comment]
You can start working on this @ishitakapoor26, 
 
Please check this URL https://letsgrowmore.in/wp-content/uploads/2021/05/growmore-removebg-preview-768x314.png for LGM - SOC logo.

Make the logo a link, clicking the logo will take the user to the LGM website https://letsgrowmore.in/soc/

**Comment by ishitakapoor26** [comment]
> You can start working on this @ishitakapoor26,
> 
> Please check this URL https://letsgrowmore.in/wp-content/uploads/2021/05/growmore-removebg-preview-768x314.png for LGM - SOC logo.
> 
> Make the logo a link, clicking the logo will take the user to the LGM website https://letsgrowmore.in/soc/

ok
