### ISSUE TITLE
Design a Logo for woodog

### ISSUE THREAD

**Issue by Aaishpra** [Feminine-Divine/Woodog#25]
### 🐣 Is your feature request related to a problem? Please describe.
Design a new logo for Woodog and place it in the project directory

**Comment by ishitakapoor26** [comment]
@Aaishpra pls assign me this issue.

**Comment by hariramjp777** [comment]
Go ahead @ishitakapoor26, Please Use white color for logo :+1:

**Comment by ishitakapoor26** [comment]
> Go ahead @ishitakapoor26, Please Use white color for logo 👍

ok

**Comment by thegautamkumarjaiswal** [comment]
You can also discuss with maintainer about logo design and styles. @hariramjp777 @Aaishpra Please enable the discussion from repository setting, will help contributor to work on features,

**Comment by khushishikhu** [comment]
Hey!! Participants. Who so ever has any ideas about the logo of Woodog can post it on the discussions.  I have enabled it. The one we like will get points.

**Comment by hariramjp777** [comment]
You can refer to the UI here created using Figma
https://www.figma.com/file/nUaDVjPxi4qn0CTZNoLj0E/Feminine-Divine-Woodog?node-id=0%3A1
It'll be good if the logo matches the background colour :+1:

**Comment by ishitakapoor26** [comment]
![WOODOG](https://user-images.githubusercontent.com/78542333/122052530-6a628f80-ce03-11eb-9041-3f1efce4efd3.png)
![WOODOG (1)](https://user-images.githubusercontent.com/78542333/122052561-71899d80-ce03-11eb-9ede-904054445c79.png)
![WOODOG (2)](https://user-images.githubusercontent.com/78542333/122052579-74848e00-ce03-11eb-9184-517909c0b4e9.png)
![WOODOG (3)](https://user-images.githubusercontent.com/78542333/122052595-78181500-ce03-11eb-9b36-d4e1ff25be45.png)
![WOODOG (4)](https://user-images.githubusercontent.com/78542333/122052609-7b130580-ce03-11eb-890e-cb9e7b88303c.png)
Pls check out above logo designs...

**Comment by Aaishpra** [comment]
I love them all 😍

**Comment by Aaishpra** [comment]
@khushishikhu can you have a look here.

**Comment by Aaishpra** [comment]
@hariramjp777 what's your choice. I like the first one.

**Comment by khushishikhu** [comment]
My vote goes to first one😍. @ishitakapoor26  you made all of them very nicely

**Comment by thegautamkumarjaiswal** [comment]
> My vote goes to first one😍. @ishitakapoor26 you made all of them very nicely

But, I am thinking is if in a logo "with person caring a dog" is more best!? @khushishikhu

**Comment by ishitakapoor26** [comment]
@thegautamkumarjaiswal i have one more but i guess it won't match the ui. Still have a look at it.
![woodog5](https://user-images.githubusercontent.com/78542333/122061585-48b9d600-ce0c-11eb-8a5a-8fe92271e7cf.PNG)

**Comment by thegautamkumarjaiswal** [comment]
> @Aaishpra @hariramjp777 @thegautamkumarjaiswal i have one more but i guess it won't match the ui. Still have a look at it.
> ![woodog5](https://user-images.githubusercontent.com/78542333/122061585-48b9d600-ce0c-11eb-8a5a-8fe92271e7cf.PNG)

Yes, You are write it won't. Lets try more! keep it

**Comment by Aaishpra** [comment]
> @Aaishpra @hariramjp777 @thegautamkumarjaiswal i have one more but i guess it won't match the ui. Still have a look at it.
> ![woodog5](https://user-images.githubusercontent.com/78542333/122061585-48b9d600-ce0c-11eb-8a5a-8fe92271e7cf.PNG)
> 

It's great just change the colours to match the ui and I think it would be perfect then

**Comment by thegautamkumarjaiswal** [comment]
> > @Aaishpra @hariramjp777 @thegautamkumarjaiswal i have one more but i guess it won't match the ui. Still have a look at it.
> > ![woodog5](https://user-images.githubusercontent.com/78542333/122061585-48b9d600-ce0c-11eb-8a5a-8fe92271e7cf.PNG)
> 
> It's great just change the colours to match the ui and I think it would be perfect then

Yes! @ishitakapoor26 I am waiting to see the final logo from all side.

**Comment by ishitakapoor26** [comment]
@thegautamkumarjaiswal @hariramjp777 @Aaishpra created another logo pls check this out.
![woodog6](https://user-images.githubusercontent.com/78542333/122071909-c386ef00-ce14-11eb-9f29-35eed55ff1ed.PNG)

**Comment by ishitakapoor26** [comment]
@thegautamkumarjaiswal @hariramjp777 @Aaishpra @khushishikhu pls check...
![woodog7](https://user-images.githubusercontent.com/78542333/122080321-d3560180-ce1b-11eb-8c2e-193844f2b2e9.PNG)

**Comment by hariramjp777** [comment]
> @hariramjp777 what's your choice. I like the first one.

Yeah @Aaishpra, @ishitakapoor26 made all of them good, I like the first and fourth :+1:

**Comment by Aaishpra** [comment]
![WOODOG](https://user-images.githubusercontent.com/78542333/122052530-6a628f80-ce03-11eb-9041-3f1efce4efd3.png)
I still like this one the best, because of it's simplicity.

**Comment by khushishikhu** [comment]
> ![WOODOG](https://user-images.githubusercontent.com/78542333/122052530-6a628f80-ce03-11eb-9041-3f1efce4efd3.png)
> I still like this one the best, because of it's simplicity.

yeah exactly. @hariramjp777  Should we finalize this

**Comment by hariramjp777** [comment]
Yeah, Let's Finalize the first one. :+1:

**Comment by khushishikhu** [comment]
> > ![WOODOG](https://user-images.githubusercontent.com/78542333/122052530-6a628f80-ce03-11eb-9041-3f1efce4efd3.png)
> > I still like this one the best, because of it's simplicity.
> 
> yeah exactly. @hariramjp777 Should we finalize this

@ishitakapoor26  We have finalized this logo. Please place it into the directory and it's your choice if you open another issue for putting the logo on the homepage of our website. Thank you for such a lovely design

**Comment by hariramjp777** [comment]
Hi @ishitakapoor26, Create a new directory `logo` inside `Woodog` i.e. `Woodog/logo` and place the finalised logo there and make a PR :+1:

**Comment by ishitakapoor26** [comment]
@hariramjp777 pls review my pr.
