### ISSUE TITLE
Beautify the Readme

### ISSUE THREAD

**Issue by Aaishpra** [Feminine-Divine/Woodog#26]
### 📚 Documentation File you'd like to improve:

- [x] README.md
- [ ] CODE_OF_CONDUCT.md
- [ ] CONTRIBUTING.md

### 💡 Describe your ideas briefly on how to improve the documentation

Although we have already have a descriptive readme for our project, it would be better if someone can organize it better and maybe add some creativity to it.
### 📹 Screenshots or Video or GIF

---

**Note:**
* Do mention if you're working on this issue under ` LGM SOC 2021 `.
* If you want to work on any issue, you should check if it has already been assigned to anyone.

**Comment by rishabhrathore055** [comment]
@Aaishpra Please Assign me this issue

**Comment by Sejal2801** [comment]
Please Assign it to me

**Comment by rishabhrathore055** [comment]
@Aaishpra pls assign me this issue.

**Comment by Aaishpra** [comment]
@rishabhrathore055 assigned
