### ISSUE TITLE
Readme File for running of the code

### ISSUE THREAD

**Issue by Shaishav0507** [Feminine-Divine/Woodog#3]
This current Readme file only displays to play with GitHub commands.
Add the commands to run on the local server so that, he/she can check the code by running it.

**Comment by hariramjp777** [comment]
> This current Readme file only displays to play with GitHub commands.
> Add the commands to run on the local server so that, he/she can check the code by running it.

Hi @Shaishav0507, Thanks for reaching out :+1:. The current `README.md` file already contains a section called `Running project on Local Server`. Can you please briefly tell me what else you wish to add?

**Comment by Shaishav0507** [comment]
To write with the proper commands and not just indicating them to do this or that.

**Comment by hariramjp777** [comment]
Go ahead @Shaishav0507

**Comment by Itashamodi** [comment]
i want it to assign it to me as well
