### ISSUE TITLE
Adding Contributors Section in readme

### ISSUE THREAD

**Issue by hariramjp777** [Feminine-Divine/Woodog#31]
### 📚 Documentation File you'd like to improve:

- [x] README.md
- [ ] CODE_OF_CONDUCT.md
- [ ] CONTRIBUTING.md

### 💡 Describe your ideas briefly on how to improve the documentation

* Adding the Contributors section in the `README.md` to display all contributors of the project. 
* It can be next to the `Open-source programs` section.
---

**Note:**
* Do mention if you're working on this issue under ` LGM SOC 2021 `.
* If you want to work on any issue, you should check if it has already been assigned to anyone.

**Comment by payaldutta** [comment]
I want to work on this issue under LGMSOC'21. Do assign if possible.
Thank You.

**Comment by hariramjp777** [comment]
Hi @payaldutta, Go ahead please

**Comment by hariramjp777** [comment]
Hi @payaldutta, Are you working on this issue?

**Comment by LizaHaddock** [comment]
Can I work on this issue?

**Comment by payaldutta** [comment]
@hariramjp777  Yes, I am working on it.

**Comment by hariramjp777** [comment]
Okay @payaldutta, Try to make a PR within today :+1:

**Comment by payaldutta** [comment]
> Okay @payaldutta, Try to make a PR within today 👍

Yes, I have made a PR.
Do review it.
Thank You.

**Comment by hariramjp777** [comment]
> > Okay @payaldutta, Try to make a PR within today +1
> 
> Yes, I have made a PR.
> Do review it.
> Thank You.

Thanks for making PR @payaldutta, I've requested some changes #45, Please check that out :+1:

**Comment by hariramjp777** [comment]
Closing this issue via #45
