### ISSUE TITLE
UI Issue - Fix Email with signup Button in Home Page

### ISSUE THREAD

**Issue by hariramjp777** [Feminine-Divine/Woodog#36]
### 🐞 Describe the Bug

* Fix `Email with signup` button on the Home page (hero and footer section)

![image](https://user-images.githubusercontent.com/58631762/121913971-7ab93280-cd4f-11eb-9eb1-77bc9fa8bf8e.png)

### 💡 Expected behaviour

It should be like the Figma design.

### 📹 Screenshots or Video or GIF

Here's the Figma link,  
https://www.figma.com/file/nUaDVjPxi4qn0CTZNoLj0E/Feminine-Divine-Woodog?node-id=0%3A1
(Refer Home, Home-Mobile Frames)

---

**Note:**
* Do mention if you're working on this issue under ` LGM SOC 2021 `.
* If you want to work on any issue, you should check if it has already been assigned to anyone.

**Comment by coding-geek21** [comment]
I would like to work on this please assign me @hariramjp777

**Comment by Sejal2801** [comment]
Assign it to me

**Comment by khushishikhu** [comment]
@Sejal2801 assigned

**Comment by Sejal2801** [comment]
Completed

**Comment by Sejal2801** [comment]
I have completed this task successfully please tell me whether its complete or not?

**Comment by Sejal2801** [comment]
This issue was assigned to me and i have completed this task .Can u tell me
did it completed or not?

**Comment by Sejal2801** [comment]
#36
