### ISSUE TITLE
UI Issue - Fix Top Navigation Bar (Make it Responsive)

### ISSUE THREAD

**Issue by hariramjp777** [Feminine-Divine/Woodog#37]
### 🐞 Describe the Bug

* Fix Top Navigation Bar and make it responsive.
* Add some transitions when clicking the hamburger icon (in mobile)

### 📹 Screenshots or Video or GIF

Here's the Figma link,
https://www.figma.com/file/nUaDVjPxi4qn0CTZNoLj0E/Feminine-Divine-%2F-Woodog?node-id=0%3A1
(Refer Home, Home-Mobile, Home-Mobile-navbar Frames)

---

**Note:**
* Do mention if you're working on this issue under ` LGM SOC 2021 `.
* If you want to work on any issue, you should check if it has already been assigned to anyone.

**Comment by Sejal2801** [comment]
Assign it to me

**Comment by khushishikhu** [comment]
@Sejal2801 assigned you

**Comment by Sejal2801** [comment]
Pleaase unssign this issue .I  have commit and pull request many times,but not happening anything,getting problem in my PC,
Sorry ..

**Comment by khushishikhu** [comment]
@Sejal2801 it's okay no problem. You can come up here whenever you feel you are ready.

**Comment by Sejal2801** [comment]
Pc is not working properly having problems ,i am not able to do .
I am starting visual code again and again it's get switched off after 5 min.
Sorry for this.

**Comment by AkshatSharma000** [comment]
If possible assign it to me.

**Comment by hariramjp777** [comment]
@AkshatSharma000 assigned you :+1:

**Comment by coding-geek21** [comment]
Can i work on this @hariramjp777 ?

**Comment by khushishikhu** [comment]
@AkshatSharma000 are you working on this? or I will assign it to someone else

**Comment by AkshatSharma000** [comment]
> @AkshatSharma000 are you working on this? or I will assign it to someone else

actually i am unable to find the related file of css and js. So, If you resolve this i can do this or else you can assign to others.

**Comment by AkshatSharma000** [comment]
> @AkshatSharma000 are you working on this? or I will assign it to someone else

also please review this #77 .
