### ISSUE TITLE
adding admins section in readme 

### ISSUE THREAD

**Issue by Ayan-thecodeking** [Feminine-Divine/Woodog#38]

**Comment by hariramjp777** [comment]
Can you please briefly explain what the issue is?

**Comment by Ayan-thecodeking** [comment]
hey @hariramjp777 please assign me this 
just want to add admins sections ....i mean maintainers section
i'll fix it for sure :)

**Comment by Sejal2801** [comment]
Please assign it to me

**Comment by Sejal2801** [comment]
Assign it to me plz

**Comment by Ayan-thecodeking** [comment]
> Hi @Ayan-thecodeking, Can you please briefly explain what the issue is?

hey @Sejal2801  i have already asked please look for another issue :)

**Comment by Ayan-thecodeking** [comment]
> Assign it to me plz

hey  @Sejal2801  i have already asked please look for another issues :)
