### ISSUE TITLE
add code-of-conduct.md file

### ISSUE THREAD

**Issue by Yash-Sakre** [Feminine-Divine/Woodog#4]
### 🐣 Is your feature request related to a problem? Please describe.
This is the code of conduct file in the repository.

This file describes all the codes of conduct while contributing to this project.

I am LGM-SOC 2021 participant. please assign this to me.

**Comment by hariramjp777** [comment]
Go ahead @Yash-Sakre

**Comment by Yash-Sakre** [comment]
please add the label of LGM-SOC'21
