### ISSUE TITLE
UI Enhancements for Login Page

### ISSUE THREAD

**Issue by hariramjp777** [Feminine-Divine/Woodog#41]
### 🐣 Is your feature request related to a problem? Please describe.

* Enhance the UI of the Login Page. (Refer Figma)

### 📹 Screenshots or Video or GIF

Here's the Figma link,
https://www.figma.com/file/nUaDVjPxi4qn0CTZNoLj0E/Feminine-Divine-Woodog?node-id=0%3A1
(Refer LOGIN Frame)

---

**Note:**
* Do mention if you're working on this issue under ` LGM SOC 2021 `.
* If you want to work on any issue, you should check if it has already been assigned to anyone.

**Comment by coding-geek21** [comment]
I would like to work on this please assign me @hariramjp777
