### ISSUE TITLE
Add a welcome bot

### ISSUE THREAD

**Issue by khushishikhu** [Feminine-Divine/Woodog#43]
### 🐣 Is your feature request related to a problem? Please describe.

Whenever someone opens a first PR. A welcome message from the bot should be displayed on their PR with a good content including some emojis

---

**Note:**
* Do mention if you're working on this issue under ` LGM SOC 2021 `.
* If you want to work on any issue, you should check if it has already been assigned to anyone.

**Comment by hariramjp777** [comment]
The welcome bot is added to this repository :star_struck: 

If you want to work on customising bot messages, Refer https://github.com/apps/the-welcome-bot :+1:

**Comment by Ayan-thecodeking** [comment]
hey let me know ..if bot is not been added yet i'll add that 
please assign me for this :)

**Comment by khushishikhu** [comment]
@Ayan-thecodeking just beautify the content

**Comment by Prakash-Haldar** [comment]
hey @khushishikhu  please assign me for this under LGM SOC 2021

**Comment by khushishikhu** [comment]
@Ayan-thecodeking are you still working or I will assign it to someone else

**Comment by Ayan-thecodeking** [comment]
I'm working @khushishikhu

**Comment by Ayan-thecodeking** [comment]
Hey @khushishikhu can u please tell me what I have to add more .. because greetings is already added there 
I'm confused which bot I have to add

**Comment by khushishikhu** [comment]
In  .gitHub/config.yml file you will find the code for welcome bit. Go through that. Modify that content for the facts that were mentioned there

**Comment by Ayan-thecodeking** [comment]
> @Ayan-thecodeking in .gitHub/config.yml file you will find the code for welcome bit. Go through that. Modify that content for the facts that were mentioned there
> For more reference https://github.com/apps/the-welcome-bot you can read this too

Okk

**Comment by Shaishav0507** [comment]
If this issue is still open, I would like to work on it.
@khushishikhu @hariramjp777
