### ISSUE TITLE
Design a new aboutUs page

### ISSUE THREAD

**Issue by Aaishpra** [Feminine-Divine/Woodog#48]
### 🐣 Is your feature request related to a problem? Please describe.

Design an about us page.

**Comment by Aaishpra** [comment]
Please keep the project theme in mind

**Comment by Shaishav0507** [comment]
Hey @Aaishpra 
I would like to work on this issue.

**Comment by hariramjp777** [comment]
Hi @Shaishav0507, Please check out this Figma file, 
https://www.figma.com/file/nUaDVjPxi4qn0CTZNoLj0E/Feminine-Divine-Woodog?node-id=0%3A1

Make sure your design matches the `background-color`, `font` and other design properties.

**Comment by Shaishav0507** [comment]
Ok

**Comment by Shaishav0507** [comment]
@Aaishpra 
Could you tell me what data I need to put in About us section ?

**Comment by Shaishav0507** [comment]
@khushishikhu 
Could you tell the data that needs to be added in this page ?

**Comment by khushishikhu** [comment]
@Shaishav0507  in about us section you can add the information about the app. And the work this website signifies. Like it basically contributes to the welfare of the street dogs in the society. Some of the content you can take a look in the Readme also

**Comment by Shaishav0507** [comment]
Ok sure.
Only the text parts need to be added right?
