### ISSUE TITLE
Design a Gallery page

### ISSUE THREAD

**Issue by Aaishpra** [Feminine-Divine/Woodog#49]
### 🐣 Is your feature request related to a problem? Please describe.

Keep the theme in mind while creating it.

---

**Note:**
* Do mention if you're working on this issue under ` LGM SOC 2021 `.
* If you want to work on any issue, you should check if it has already been assigned to anyone.

**Comment by Prakash-Haldar** [comment]
hey @Aaishpra please assign me for this under LGM SOC 2021

**Comment by hariramjp777** [comment]
Hi @Prakash-Haldar, Please check out this Figma file,
https://www.figma.com/file/nUaDVjPxi4qn0CTZNoLj0E/Feminine-Divine-Woodog?node-id=0%3A1

Make sure your design matches the `background-color`, `font` and other design properties.

**Comment by Prakash-Haldar** [comment]
Sir/Mam Please mention the file name or the coding section, Where all the codes of @Design a gallery page are stored  in GitHub file

**Comment by Aaishpra** [comment]
No need to call us sir/mam @Prakash-Haldar , and you can create a new file named `gallery.html`  [here](https://github.com/Feminine-Divine/Woodog/tree/master/Woodog/templates/woodogdata)

**Comment by coding-geek21** [comment]
Can I also work on this @hariramjp777

**Comment by kumarishalini6** [comment]
if no one is working in this issue can i work @khushishikhu  @Aaishpra ??

**Comment by Aaishpra** [comment]
@coding-geek21 are you working here?

**Comment by Prakash-Haldar** [comment]
You can assign this project to someone . Currently my semester exams r going on

**Comment by coding-geek21** [comment]
> @coding-geek21 are you working here?

Yeah
