### ISSUE TITLE
Making login/logout route. 

### ISSUE THREAD

**Issue by MuhammadAbdullah-hash** [Feminine-Divine/Woodog#52]
### 💡 Describe the solution you'd like
I want to make a login route on the home page so that the user can direct to the login page + when the user is logged in and rooted back it will have the option to log out and his name will be displayed.

**Note:**
Kindly assign me this issue under LGM-soc'21

**Comment by khushishikhu** [comment]
@MuhammadAbdullah-hash  assigned
