### ISSUE TITLE
Design a logo for Feminine Divine

### ISSUE THREAD

**Issue by khushishikhu** [Feminine-Divine/Woodog#58]
### 🐣 Is your feature request related to a problem? Please describe.

Design a new logo for the feminine divine and place it in the directory.

### 💡 Describe the solution you'd like

Try to make the logo in a way that depicts the moto of the organization

---

**Note:**
* Do mention if you're working on this issue under ` LGM SOC 2021 `.
* If you want to work on any issue, you should check if it has already been assigned to anyone.

**Comment by ishitakapoor26** [comment]
@khushishikhu pls assign me this issue.

**Comment by ishitakapoor26** [comment]
@khushishikhu @thegautamkumarjaiswal @hariramjp777 can you please describe what are your requirements like colors preferred, motive of Feminine Divine, so that I can try my best for logo.

**Comment by khushishikhu** [comment]
@ishitakapoor26  This is the website https://khushis-fantabulous-project.webflow.io/ you will find the motive of the organization. And about the colours and stuff, it is all your choice whichever you finds the best

**Comment by ishitakapoor26** [comment]
@khushishikhu pls check logo
![feminine divine logo1](https://user-images.githubusercontent.com/78542333/122544058-0aa9f580-d04a-11eb-99db-895799810fc7.PNG)

**Comment by ishitakapoor26** [comment]
![feminine2](https://user-images.githubusercontent.com/78542333/122544256-4349cf00-d04a-11eb-8844-2da24167faab.PNG)

@khushishikhu @hariramjp777 pls suggest if any changes related to color is to be made and also i'll remove background too.

**Comment by ishitakapoor26** [comment]
![feminine3](https://user-images.githubusercontent.com/78542333/122544571-93289600-d04a-11eb-84a6-16e80a90cfe1.PNG)

**Comment by ishitakapoor26** [comment]
@khushishikhu @hariramjp777 will animated logo work? I have created one just check it out...

https://user-images.githubusercontent.com/78542333/122546446-93c22c00-d04c-11eb-9a4a-46c63ab33c0e.mp4

**Comment by ishitakapoor26** [comment]
![FEMININE DIVINE (1)](https://user-images.githubusercontent.com/78542333/122552093-7d6b9e80-d053-11eb-9f18-80f5d652bf05.png)

**Comment by hariramjp777** [comment]
@ishitakapoor26 The animated logo looks good :star_struck:

**Comment by ishitakapoor26** [comment]
![FEMININE DIVINE (2)](https://user-images.githubusercontent.com/78542333/122554792-0e904480-d057-11eb-96bc-de5d607d2ad8.png)

**Comment by ishitakapoor26** [comment]
![FEMININE DIVINE (1)](https://user-images.githubusercontent.com/78542333/122556562-4b5d3b00-d059-11eb-982e-f2732097ac56.gif)

A little variation in animated one pls check.

**Comment by ishitakapoor26** [comment]
![FEMININE DIVINE (2)](https://user-images.githubusercontent.com/78542333/122557550-9035a180-d05a-11eb-9cfa-6bd3c62a8edd.gif)

**Comment by khushishikhu** [comment]
@ishitakapoor26 Thank you very much for such lovely logos. I like the last two logos you can put an animated one in the project directory. @hariramjp777 @Aaishpra  Please give your opinions also which one do you like?

**Comment by hariramjp777** [comment]
> ![img](https://user-images.githubusercontent.com/78542333/122554792-0e904480-d057-11eb-96bc-de5d607d2ad8.png)

This one looks good

**Comment by Aaishpra** [comment]
Agreed let's just finalize the above pne
