### ISSUE TITLE
Create contributing.md

### ISSUE THREAD

**Issue by hariramjp777** [Feminine-Divine/Woodog#6]
### 🐣 Is your feature request related to a problem? Please describe.

Create `contributing.md` file that explains the following:

* How to open issues
* How to start working on issues
* How to make a PR

---

**Note:**
* Do mention if you're working on this issue under ` LGM SOC 2021 `.
* If you want to work on any issue, you should check if it has already been assigned to anyone.

**Comment by coding-geek21** [comment]
I would like to work on this please assign me

**Comment by hariramjp777** [comment]
You can start working on this issue @coding-geek21

**Comment by coding-geek21** [comment]
> You can start working on this issue @coding-geek21 
> 

Thank you :)
