### ISSUE TITLE
Automatic updation of Footer Copyright Year

### ISSUE THREAD

**Issue by Shaishav0507** [Feminine-Divine/Woodog#60]
### 🐣 Is your feature request related to a problem? Please describe.

Hey @Aaishpra 
I would like to add script where footer copyright year changes automatically.
In current scenario we need to change every time 
Please assign it to me. 
Thanks.

### 📹 Screenshots or Video or GIF

---

**Note:**
I am working uner LGM SOC 2021 `.

**Comment by hariramjp777** [comment]
Hi @Shaishav0507, Assigned :+1:
