### ISSUE TITLE
Add logo to website

### ISSUE THREAD

**Issue by ishitakapoor26** [Feminine-Divine/Woodog#61]
Adding finalized logo to woodog website.

**Comment by ishitakapoor26** [comment]
@hariramjp777 pls assign me this issue.

**Comment by hariramjp777** [comment]
@ishitakapoor26, Assigned you :+1:

**Comment by jayant766** [comment]
please assign it to me under LGM-SOC'21

**Comment by ishitakapoor26** [comment]
> please assign it to me under LGM-SOC'21

Hey I'm already working on it @jayant766
