### ISSUE TITLE
Refactor Template Files structure

### ISSUE THREAD

**Issue by hariramjp777** [Feminine-Divine/Woodog#64]
#### Refactor Template Files Structure

* In the `templates/partials`, three files should be there, `base.html`, `header.html` and `footer.html`.
* `base.html` should only contain HTML Boilerplate with `body` containing the Django block.
Like this,
```html
<!DOCTYPE html>
<html>
<head>...</head>
<body>
{% block content %}
{% endblock %}
</body>
</html>
```
* `header.html` should contain `<header>...</header>`
* `footer.html` should contain `<footer>...</footer>`
* Above three files should be in `templates/partials` so that we can make it available to all other core templates.
* Core templates like `home.html`, `signup.html`, `login.html` and others should extend the base template and include the header and footer templates. (Make use of Django `extends` and `include` here)

---

**Note:**
* Do mention if you're working on this issue under ` LGM SOC 2021 `.
* If you want to work on any issue, you should check if it has already been assigned to anyone.

**Comment by coding-geek21** [comment]
I would like to work on it, please assign me @hariramjp777
