### ISSUE TITLE
Design Contact Us page

### ISSUE THREAD

**Issue by Shaishav0507** [Feminine-Divine/Woodog#68]
### 🐣 Is your feature request related to a problem? Please describe.

Hey @hariramjp777 @khushishikhu 
I would like to make new contact us page.
Please assign it to me.
Thanks.

### 📹 Screenshots or Video or GIF

---

**Note:**
* Do mention if you're working on this issue under ` LGM SOC 2021 `.
* If you want to work on any issue, you should check if it has already been assigned to anyone.

**Comment by khushishikhu** [comment]
@Shaishav0507 assigned you. Please look for the figma template for taking the colour ideas

**Comment by Shaishav0507** [comment]
Please provide the content also that needs to be added

**Comment by hariramjp777** [comment]
@Shaishav0507, For contact there should be a form asking name, email, subject, a message from the user

**Comment by Shaishav0507** [comment]
> @Shaishav0507, For contact there should be a form asking name, email, subject, a message from the user

Ok 👍

**Comment by coding-geek21** [comment]
@hariramjp777 Can I work on this?

**Comment by Shaishav0507** [comment]
> @hariramjp777 Can I work on this?

@coding-geek21 I have done it. Just need to make PR. @hariramjp777
