### ISSUE TITLE
Add Feedback Page

### ISSUE THREAD

**Issue by ishitakapoor26** [Feminine-Divine/Woodog#70]
Add feedback page

**Comment by ishitakapoor26** [comment]
@hariramjp777 @khushishikhu pls assign me this issue.

**Comment by khushishikhu** [comment]
@ishitakapoor26 assigned

**Comment by kumarishalini6** [comment]
If no one is working can I work on this issue
@khushishikhu

**Comment by ishitakapoor26** [comment]
@kumarishalini6 i'm working on this issue. Actually, I had my end sem exams last week so I wasn't able to work on it but now I'm almost done with it.

**Comment by kumarishalini6** [comment]
It's ok
