### ISSUE TITLE
Create a logo for feminine-divine

### ISSUE THREAD

**Issue by Aaishpra** [Feminine-Divine/Woodog#75]
### 🐣 Is your feature request related to a problem? Please describe.
We need a new logo for our organisation, if someone has any idea. They can post here.

### 💡 Describe the solution you'd like
A new logo for feminine divine

### ❓ Describe alternatives you've considered
None

### 📹 Screenshots or Video or GIF

<!-- Attac
---

**Note:**
* Do mention if you're working on this issue under ` LGM SOC 2021 `.
* If you want to work on any issue, you should check if it has already been assigned to anyone.

**Comment by payaldutta** [comment]
I want to work on this. 
Do assign me if possible. 
Thank you.

**Comment by ishitakapoor26** [comment]
Hey @payaldutta this issue is already assigned to me. Pls check issues section and then create new issues. Good Luck!

**Comment by ishitakapoor26** [comment]
@Aaishpra this issue is already assigned to me by @khushishikhu then why have you created same issue?

**Comment by hariramjp777** [comment]
@Aaishpra, This issue is already open #58.
