### ISSUE TITLE
Updating Register Page

### ISSUE THREAD

**Issue by AkshatSharma000** [Feminine-Divine/Woodog#78]
### 🐣 Is your feature request related to a problem? Please describe.

Register page is looking to dull and not responsive too.

### 💡 Describe the solution you'd like

I will develop an attractive register page compatible for responsive interaction.

### 📹 Screenshots or Video or GIF

---

**Note:**
* Do mention if you're working on this issue under ` LGM SOC 2021 `.
* If you want to work on any issue, you should check if it has already been assigned to anyone.

**Comment by hariramjp777** [comment]
@AkshatSharma000, Work on this issue :+1:. Refer the <a href="https://www.figma.com/file/nUaDVjPxi4qn0CTZNoLj0E/Feminine-Divine-Woodog?node-id=0%3A1">Figma</a> (SIGNUP Frame). I don't want the UI to be changed. Enhance the page by fixing style issues on the page and making it responsive.

**Comment by hariramjp777** [comment]
@AkshatSharma000, Are you an `LGMSOC 2021` Participant?

**Comment by AkshatSharma000** [comment]
> @AkshatSharma000, Work on this issue 👍. Refer the [Figma](https://www.figma.com/file/nUaDVjPxi4qn0CTZNoLj0E/Feminine-Divine-Woodog?node-id=0%3A1) (SIGNUP Frame). I don't want the UI to be changed.
> Enhance the page by fixing style issues on the page and making it responsive.

I can develop the same as per your frame but i cannot embed the dtl into it, if you can do it I will create as per your expectation.

**Comment by hariramjp777** [comment]
> > @AkshatSharma000, Work on this issue +1. Refer the [Figma](https://www.figma.com/file/nUaDVjPxi4qn0CTZNoLj0E/Feminine-Divine-Woodog?node-id=0%3A1) (SIGNUP Frame). I don't want the UI to be changed.
> > Enhance the page by fixing style issues on the page and making it responsive.
> 
> I can develop the same as per your frame but i am unable to embed the dtl into it, if you can do it I will create as per your expectation.

Hi @AkshatSharma000, what is dtl?

**Comment by AkshatSharma000** [comment]
> > ... **i am unable to embed the dtl into it**, if you can do it I will create as per your expectation.
> 
> 
> 
> Hi @AkshatSharma000, what is dtl?

Django Template Language thats embedded in the code to link the model based view

**Comment by hariramjp777** [comment]
@AkshatSharma000, Can you please brief the problem here you're facing?

Check out the <a href="https://github.com/Feminine-Divine/Woodog/blob/master/README.md">`README.md`</a> to setup the project.

**Comment by AkshatSharma000** [comment]
> @AkshatSharma000, Can you please brief the problem here you're facing?
> 
> 
> 
> Check out the <a href="https://github.com/Feminine-Divine/Woodog/blob/master/README.md">`README.md`</a> to setup the project.

Actually I will develop whole frontend but i am not able to embed django view based modal in it.So if you assure me for embedding by your side , I can start working on it.

**Comment by AkshatSharma000** [comment]
> @AkshatSharma000, Can you please brief the problem here you're facing?
> 
> 
> 
> Check out the <a href="https://github.com/Feminine-Divine/Woodog/blob/master/README.md">`README.md`</a> to setup the project.

Whole front end has been messed up in the project making fully compatible and organised frontend is the current need.

**Comment by Aaishpra** [comment]
> > @AkshatSharma000, Can you please brief the problem here you're facing?
> > Check out the [`README.md`](https://github.com/Feminine-Divine/Woodog/blob/master/README.md) to setup the project.
> 
> Whole front end has been messed up in the project making fully compatible and organised frontend is the current need.

Agreed, Can you please send a PR for the same?

**Comment by AkshatSharma000** [comment]
> > > @AkshatSharma000, Can you please brief the problem here you're facing?
> > > Check out the [`README.md`](https://github.com/Feminine-Divine/Woodog/blob/master/README.md) to setup the project.
> > 
> > 
> > Whole front end has been messed up in the project making fully compatible and organised frontend is the current need.
> 
> Agreed, Can you please send a PR for the same?

I have already being assigned for it. All I need your favour to embed django templates language in it.

**Comment by Sejal2801** [comment]
Assign it to me

**Comment by coding-geek21** [comment]
Can I work on this issue?

**Comment by Sejal2801** [comment]
Assign it to me

**Comment by hariramjp777** [comment]
@Sejal2801 assigned.

**Comment by Sejal2801** [comment]
Is there any update??

**Comment by Sejal2801** [comment]
Okay Now its done? still its showing that you have assign it to me
but I have completed my work..
