### ISSUE TITLE
add some badges to README

### ISSUE THREAD

**Issue by Umesh-01** [Feminine-Divine/Woodog#80]
### 📚 Documentation File you'd like to improve:
add badges to the top of readme.md file, since the badges will be colorful and more attractive at the top of README.md file than the text the users will like it and after linking the badges it will also help them to navigate to different sections/ webpages like PRs, issues, contributors, etc.

- [x] README.md
- [ ] CODE_OF_CONDUCT.md
- [ ] CONTRIBUTING.md

![image](https://user-images.githubusercontent.com/83420185/122651241-29e17980-d155-11eb-992c-5b4addd4956d.png)

### 💡 Describe your ideas briefly on how to improve the documentation
I will add some badges and also will add links related to them to the top so that the README.md file will look more interactive and awesome.

### Working as/under
- [x] LGMSOC
- [ ] Contributor

**Note:**
* Do mention if you're working on this issue under ` LGM SOC 2021 `.
* If you want to work on any issue, you should check if it has already been assigned to anyone.

**Comment by Umesh-01** [comment]
@khushishikhu @coding-geek21 should I work on this??

**Comment by khushishikhu** [comment]
@Umesh-01 go ahead

**Comment by hariramjp777** [comment]
@Umesh-01 assigned :+1:
