### ISSUE TITLE
Improvement in the UI of About Us

### ISSUE THREAD

**Issue by khushishikhu** [Feminine-Divine/Woodog#83]
### 🐞 Describe the Bug

currently the UIof about us page is not so attractive. we would like to have a good UI for that.

### 💡 To Reproduce

---

**Note:**
* Do mention if you're working on this issue under ` LGM SOC 2021 `.
* If you want to work on any issue, you should check if it has already been assigned to anyone.

**Comment by coding-geek21** [comment]
I would like to work on this please assign me @khushishikhu @hariramjp777

**Comment by khushishikhu** [comment]
@coding-geek21 assigned
