### ISSUE TITLE
Rest_Api in contact us 

### ISSUE THREAD

**Issue by 7saikat7** [Feminine-Divine/Woodog#88]
### 🐣 Is your feature request related to a problem? Please describe.

It will be highly useful if we integrate a rest api in the contact us form , so later on in case of colaboration many other apps or website can use this api to submit a contact request 

### 💡 Describe the solution you'd like

this api can help to interact with other web apps without changing the code , so it can be really useful in future!
Later on we can change the authentication system with rest api !

### 📹 Screenshots or Video or GIF

---

**Note:**
* Do mention if you're working on this issue under ` LGM SOC 2021 `.
* If you want to work on any issue, you should check if it has already been assigned to anyone.

**Comment by 7saikat7** [comment]
This is a suggestion or enhancement to this beautiful project, if it's valid issue , i would like to work on rest API, I just have kickstarted with this recently!

**Comment by khushishikhu** [comment]
@7saikat7  assigned. Go ahead
