### ISSUE TITLE
UI Enhancement for Contact us Page.

### ISSUE THREAD

**Issue by hariramjp777** [Feminine-Divine/Woodog#90]
### 🐣 Is your feature request related to a problem? Please describe.

UI Enhancement for the `contact` page.

**Note:**
* Do mention if you're working on this issue under ` LGM SOC 2021 `.
* If you want to work on any issue, you should check if it has already been assigned to anyone.

**Comment by coding-geek21** [comment]
I would like to work on this please assign me @hariramjp777

**Comment by hariramjp777** [comment]
Go ahead @coding-geek21

**Comment by khushishikhu** [comment]
@coding-geek21 also make that page directed when we click on the contact page. There is also some error that page isn't follow the router with localhost:8000/..../
