### ISSUE TITLE
Add scroll to top button

### ISSUE THREAD

**Issue by coding-geek21** [Feminine-Divine/Woodog#91]
### 🐣 Is your feature request related to a problem? Please describe.

Add scroll to top button

### 📹 Screenshots or Video or GIF

---

please assign me under LGM SOC'21

**Note:**
* Do mention if you're working on this issue under ` LGM SOC 2021 `.
* If you want to work on any issue, you should check if it has already been assigned to anyone.

**Comment by hariramjp777** [comment]
@coding-geek21 assigned :+1:
