### ISSUE TITLE
Add a favicon 

### ISSUE THREAD

**Issue by coding-geek21** [Feminine-Divine/Woodog#93]
### 🐣 Is your feature request related to a problem? Please describe.

Add a favicon 

### 📹 Screenshots or Video or GIF

---

I would like to work on this please assign me under LGM SOC 2021

**Note:**
* Do mention if you're working on this issue under ` LGM SOC 2021 `.
* If you want to work on any issue, you should check if it has already been assigned to anyone.

**Comment by hariramjp777** [comment]
@coding-geek21 assigned :+1:
