### ISSUE TITLE
Change Password Page

### ISSUE THREAD

**Issue by hariramjp777** [Feminine-Divine/Woodog#97]
### 🐣 Is your feature request related to a problem? Please describe.

* Adding Change Password Page.

### 💡 Describe the solution you'd like

* Only People who logged in can access this page.
* It should be a form containing two inputs `Current Password` and `New Password` and a submit button.
* Changing the user's password if the current password is correct (matches).

---

**Note:**
* Do mention if you're working on this issue under ` LGM SOC 2021 `.
* If you want to work on any issue, you should check if it has already been assigned to anyone.

**Comment by coding-geek21** [comment]
I would like to work on this , please assign me @hariramjp777

**Comment by hariramjp777** [comment]
@coding-geek21 :+1: assigned
