### ISSUE TITLE
Enhance the alert messages

### ISSUE THREAD

**Issue by coding-geek21** [Feminine-Divine/Woodog#99]
### 🐣 Is your feature request related to a problem? Please describe.

Enhance the alert messages like success and error messages displayed in webpages 

### 📹 Screenshots or Video or GIF

---

**Note:**
* Do mention if you're working on this issue under ` LGM SOC 2021 `.
* If you want to work on any issue, you should check if it has already been assigned to anyone.

**Comment by hariramjp777** [comment]
@coding-geek21, :+1: assigned.
